// ADC_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module ADC_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                  //                                clk_0_clk.clk
		input  wire        master_0_clk_reset_reset_bridge_in_reset_reset, // master_0_clk_reset_reset_bridge_in_reset.reset
		input  wire        mm_bridge_0_reset_reset_bridge_in_reset_reset,  //  mm_bridge_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] master_0_master_address,                        //                          master_0_master.address
		output wire        master_0_master_waitrequest,                    //                                         .waitrequest
		input  wire [3:0]  master_0_master_byteenable,                     //                                         .byteenable
		input  wire        master_0_master_read,                           //                                         .read
		output wire [31:0] master_0_master_readdata,                       //                                         .readdata
		output wire        master_0_master_readdatavalid,                  //                                         .readdatavalid
		input  wire        master_0_master_write,                          //                                         .write
		input  wire [31:0] master_0_master_writedata,                      //                                         .writedata
		input  wire [9:0]  mm_bridge_0_m0_address,                         //                           mm_bridge_0_m0.address
		output wire        mm_bridge_0_m0_waitrequest,                     //                                         .waitrequest
		input  wire [0:0]  mm_bridge_0_m0_burstcount,                      //                                         .burstcount
		input  wire [1:0]  mm_bridge_0_m0_byteenable,                      //                                         .byteenable
		input  wire        mm_bridge_0_m0_read,                            //                                         .read
		output wire [15:0] mm_bridge_0_m0_readdata,                        //                                         .readdata
		output wire        mm_bridge_0_m0_readdatavalid,                   //                                         .readdatavalid
		input  wire        mm_bridge_0_m0_write,                           //                                         .write
		input  wire [15:0] mm_bridge_0_m0_writedata,                       //                                         .writedata
		input  wire        mm_bridge_0_m0_debugaccess,                     //                                         .debugaccess
		output wire [0:0]  modular_adc_0_sequencer_csr_address,            //              modular_adc_0_sequencer_csr.address
		output wire        modular_adc_0_sequencer_csr_write,              //                                         .write
		output wire        modular_adc_0_sequencer_csr_read,               //                                         .read
		input  wire [31:0] modular_adc_0_sequencer_csr_readdata,           //                                         .readdata
		output wire [31:0] modular_adc_0_sequencer_csr_writedata           //                                         .writedata
	);

	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_waitrequest;    // mm_bridge_0_m0_agent:av_waitrequest -> mm_bridge_0_m0_translator:uav_waitrequest
	wire   [15:0] mm_bridge_0_m0_translator_avalon_universal_master_0_readdata;       // mm_bridge_0_m0_agent:av_readdata -> mm_bridge_0_m0_translator:uav_readdata
	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_debugaccess;    // mm_bridge_0_m0_translator:uav_debugaccess -> mm_bridge_0_m0_agent:av_debugaccess
	wire   [31:0] mm_bridge_0_m0_translator_avalon_universal_master_0_address;        // mm_bridge_0_m0_translator:uav_address -> mm_bridge_0_m0_agent:av_address
	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_read;           // mm_bridge_0_m0_translator:uav_read -> mm_bridge_0_m0_agent:av_read
	wire    [1:0] mm_bridge_0_m0_translator_avalon_universal_master_0_byteenable;     // mm_bridge_0_m0_translator:uav_byteenable -> mm_bridge_0_m0_agent:av_byteenable
	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_readdatavalid;  // mm_bridge_0_m0_agent:av_readdatavalid -> mm_bridge_0_m0_translator:uav_readdatavalid
	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_lock;           // mm_bridge_0_m0_translator:uav_lock -> mm_bridge_0_m0_agent:av_lock
	wire          mm_bridge_0_m0_translator_avalon_universal_master_0_write;          // mm_bridge_0_m0_translator:uav_write -> mm_bridge_0_m0_agent:av_write
	wire   [15:0] mm_bridge_0_m0_translator_avalon_universal_master_0_writedata;      // mm_bridge_0_m0_translator:uav_writedata -> mm_bridge_0_m0_agent:av_writedata
	wire    [1:0] mm_bridge_0_m0_translator_avalon_universal_master_0_burstcount;     // mm_bridge_0_m0_translator:uav_burstcount -> mm_bridge_0_m0_agent:av_burstcount
	wire          master_0_master_translator_avalon_universal_master_0_waitrequest;   // master_0_master_agent:av_waitrequest -> master_0_master_translator:uav_waitrequest
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_readdata;      // master_0_master_agent:av_readdata -> master_0_master_translator:uav_readdata
	wire          master_0_master_translator_avalon_universal_master_0_debugaccess;   // master_0_master_translator:uav_debugaccess -> master_0_master_agent:av_debugaccess
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_address;       // master_0_master_translator:uav_address -> master_0_master_agent:av_address
	wire          master_0_master_translator_avalon_universal_master_0_read;          // master_0_master_translator:uav_read -> master_0_master_agent:av_read
	wire    [3:0] master_0_master_translator_avalon_universal_master_0_byteenable;    // master_0_master_translator:uav_byteenable -> master_0_master_agent:av_byteenable
	wire          master_0_master_translator_avalon_universal_master_0_readdatavalid; // master_0_master_agent:av_readdatavalid -> master_0_master_translator:uav_readdatavalid
	wire          master_0_master_translator_avalon_universal_master_0_lock;          // master_0_master_translator:uav_lock -> master_0_master_agent:av_lock
	wire          master_0_master_translator_avalon_universal_master_0_write;         // master_0_master_translator:uav_write -> master_0_master_agent:av_write
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_writedata;     // master_0_master_translator:uav_writedata -> master_0_master_agent:av_writedata
	wire    [2:0] master_0_master_translator_avalon_universal_master_0_burstcount;    // master_0_master_translator:uav_burstcount -> master_0_master_agent:av_burstcount
	wire          rsp_mux_001_src_valid;                                              // rsp_mux_001:src_valid -> master_0_master_agent:rp_valid
	wire  [101:0] rsp_mux_001_src_data;                                               // rsp_mux_001:src_data -> master_0_master_agent:rp_data
	wire          rsp_mux_001_src_ready;                                              // master_0_master_agent:rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                            // rsp_mux_001:src_channel -> master_0_master_agent:rp_channel
	wire          rsp_mux_001_src_startofpacket;                                      // rsp_mux_001:src_startofpacket -> master_0_master_agent:rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                                        // rsp_mux_001:src_endofpacket -> master_0_master_agent:rp_endofpacket
	wire   [31:0] modular_adc_0_sequencer_csr_agent_m0_readdata;                      // modular_adc_0_sequencer_csr_translator:uav_readdata -> modular_adc_0_sequencer_csr_agent:m0_readdata
	wire          modular_adc_0_sequencer_csr_agent_m0_waitrequest;                   // modular_adc_0_sequencer_csr_translator:uav_waitrequest -> modular_adc_0_sequencer_csr_agent:m0_waitrequest
	wire          modular_adc_0_sequencer_csr_agent_m0_debugaccess;                   // modular_adc_0_sequencer_csr_agent:m0_debugaccess -> modular_adc_0_sequencer_csr_translator:uav_debugaccess
	wire   [31:0] modular_adc_0_sequencer_csr_agent_m0_address;                       // modular_adc_0_sequencer_csr_agent:m0_address -> modular_adc_0_sequencer_csr_translator:uav_address
	wire    [3:0] modular_adc_0_sequencer_csr_agent_m0_byteenable;                    // modular_adc_0_sequencer_csr_agent:m0_byteenable -> modular_adc_0_sequencer_csr_translator:uav_byteenable
	wire          modular_adc_0_sequencer_csr_agent_m0_read;                          // modular_adc_0_sequencer_csr_agent:m0_read -> modular_adc_0_sequencer_csr_translator:uav_read
	wire          modular_adc_0_sequencer_csr_agent_m0_readdatavalid;                 // modular_adc_0_sequencer_csr_translator:uav_readdatavalid -> modular_adc_0_sequencer_csr_agent:m0_readdatavalid
	wire          modular_adc_0_sequencer_csr_agent_m0_lock;                          // modular_adc_0_sequencer_csr_agent:m0_lock -> modular_adc_0_sequencer_csr_translator:uav_lock
	wire   [31:0] modular_adc_0_sequencer_csr_agent_m0_writedata;                     // modular_adc_0_sequencer_csr_agent:m0_writedata -> modular_adc_0_sequencer_csr_translator:uav_writedata
	wire          modular_adc_0_sequencer_csr_agent_m0_write;                         // modular_adc_0_sequencer_csr_agent:m0_write -> modular_adc_0_sequencer_csr_translator:uav_write
	wire    [2:0] modular_adc_0_sequencer_csr_agent_m0_burstcount;                    // modular_adc_0_sequencer_csr_agent:m0_burstcount -> modular_adc_0_sequencer_csr_translator:uav_burstcount
	wire          modular_adc_0_sequencer_csr_agent_rf_source_valid;                  // modular_adc_0_sequencer_csr_agent:rf_source_valid -> modular_adc_0_sequencer_csr_agent_rsp_fifo:in_valid
	wire  [102:0] modular_adc_0_sequencer_csr_agent_rf_source_data;                   // modular_adc_0_sequencer_csr_agent:rf_source_data -> modular_adc_0_sequencer_csr_agent_rsp_fifo:in_data
	wire          modular_adc_0_sequencer_csr_agent_rf_source_ready;                  // modular_adc_0_sequencer_csr_agent_rsp_fifo:in_ready -> modular_adc_0_sequencer_csr_agent:rf_source_ready
	wire          modular_adc_0_sequencer_csr_agent_rf_source_startofpacket;          // modular_adc_0_sequencer_csr_agent:rf_source_startofpacket -> modular_adc_0_sequencer_csr_agent_rsp_fifo:in_startofpacket
	wire          modular_adc_0_sequencer_csr_agent_rf_source_endofpacket;            // modular_adc_0_sequencer_csr_agent:rf_source_endofpacket -> modular_adc_0_sequencer_csr_agent_rsp_fifo:in_endofpacket
	wire          modular_adc_0_sequencer_csr_agent_rsp_fifo_out_valid;               // modular_adc_0_sequencer_csr_agent_rsp_fifo:out_valid -> modular_adc_0_sequencer_csr_agent:rf_sink_valid
	wire  [102:0] modular_adc_0_sequencer_csr_agent_rsp_fifo_out_data;                // modular_adc_0_sequencer_csr_agent_rsp_fifo:out_data -> modular_adc_0_sequencer_csr_agent:rf_sink_data
	wire          modular_adc_0_sequencer_csr_agent_rsp_fifo_out_ready;               // modular_adc_0_sequencer_csr_agent:rf_sink_ready -> modular_adc_0_sequencer_csr_agent_rsp_fifo:out_ready
	wire          modular_adc_0_sequencer_csr_agent_rsp_fifo_out_startofpacket;       // modular_adc_0_sequencer_csr_agent_rsp_fifo:out_startofpacket -> modular_adc_0_sequencer_csr_agent:rf_sink_startofpacket
	wire          modular_adc_0_sequencer_csr_agent_rsp_fifo_out_endofpacket;         // modular_adc_0_sequencer_csr_agent_rsp_fifo:out_endofpacket -> modular_adc_0_sequencer_csr_agent:rf_sink_endofpacket
	wire          cmd_mux_src_valid;                                                  // cmd_mux:src_valid -> modular_adc_0_sequencer_csr_agent:cp_valid
	wire  [101:0] cmd_mux_src_data;                                                   // cmd_mux:src_data -> modular_adc_0_sequencer_csr_agent:cp_data
	wire          cmd_mux_src_ready;                                                  // modular_adc_0_sequencer_csr_agent:cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                // cmd_mux:src_channel -> modular_adc_0_sequencer_csr_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                          // cmd_mux:src_startofpacket -> modular_adc_0_sequencer_csr_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                            // cmd_mux:src_endofpacket -> modular_adc_0_sequencer_csr_agent:cp_endofpacket
	wire          mm_bridge_0_m0_agent_cp_valid;                                      // mm_bridge_0_m0_agent:cp_valid -> router:sink_valid
	wire   [83:0] mm_bridge_0_m0_agent_cp_data;                                       // mm_bridge_0_m0_agent:cp_data -> router:sink_data
	wire          mm_bridge_0_m0_agent_cp_ready;                                      // router:sink_ready -> mm_bridge_0_m0_agent:cp_ready
	wire          mm_bridge_0_m0_agent_cp_startofpacket;                              // mm_bridge_0_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          mm_bridge_0_m0_agent_cp_endofpacket;                                // mm_bridge_0_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          master_0_master_agent_cp_valid;                                     // master_0_master_agent:cp_valid -> router_001:sink_valid
	wire  [101:0] master_0_master_agent_cp_data;                                      // master_0_master_agent:cp_data -> router_001:sink_data
	wire          master_0_master_agent_cp_ready;                                     // router_001:sink_ready -> master_0_master_agent:cp_ready
	wire          master_0_master_agent_cp_startofpacket;                             // master_0_master_agent:cp_startofpacket -> router_001:sink_startofpacket
	wire          master_0_master_agent_cp_endofpacket;                               // master_0_master_agent:cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                               // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [101:0] router_001_src_data;                                                // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                               // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                             // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                                       // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                                         // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          modular_adc_0_sequencer_csr_agent_rp_valid;                         // modular_adc_0_sequencer_csr_agent:rp_valid -> router_002:sink_valid
	wire  [101:0] modular_adc_0_sequencer_csr_agent_rp_data;                          // modular_adc_0_sequencer_csr_agent:rp_data -> router_002:sink_data
	wire          modular_adc_0_sequencer_csr_agent_rp_ready;                         // router_002:sink_ready -> modular_adc_0_sequencer_csr_agent:rp_ready
	wire          modular_adc_0_sequencer_csr_agent_rp_startofpacket;                 // modular_adc_0_sequencer_csr_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          modular_adc_0_sequencer_csr_agent_rp_endofpacket;                   // modular_adc_0_sequencer_csr_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                               // router_002:src_valid -> rsp_demux:sink_valid
	wire  [101:0] router_002_src_data;                                                // router_002:src_data -> rsp_demux:sink_data
	wire          router_002_src_ready;                                               // rsp_demux:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                             // router_002:src_channel -> rsp_demux:sink_channel
	wire          router_002_src_startofpacket;                                       // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_002_src_endofpacket;                                         // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                               // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [101:0] cmd_demux_src0_data;                                                // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                               // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                             // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                       // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                         // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                           // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [101:0] cmd_demux_001_src0_data;                                            // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire          cmd_demux_001_src0_ready;                                           // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                                         // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire          cmd_demux_001_src0_startofpacket;                                   // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                                     // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                                               // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [101:0] rsp_demux_src0_data;                                                // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                               // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                             // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                       // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                         // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                                               // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [101:0] rsp_demux_src1_data;                                                // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire          rsp_demux_src1_ready;                                               // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                                             // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire          rsp_demux_src1_startofpacket;                                       // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          rsp_demux_src1_endofpacket;                                         // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire          rsp_mux_src_valid;                                                  // rsp_mux:src_valid -> mm_bridge_0_m0_rsp_width_adapter:in_valid
	wire  [101:0] rsp_mux_src_data;                                                   // rsp_mux:src_data -> mm_bridge_0_m0_rsp_width_adapter:in_data
	wire          rsp_mux_src_ready;                                                  // mm_bridge_0_m0_rsp_width_adapter:in_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                // rsp_mux:src_channel -> mm_bridge_0_m0_rsp_width_adapter:in_channel
	wire          rsp_mux_src_startofpacket;                                          // rsp_mux:src_startofpacket -> mm_bridge_0_m0_rsp_width_adapter:in_startofpacket
	wire          rsp_mux_src_endofpacket;                                            // rsp_mux:src_endofpacket -> mm_bridge_0_m0_rsp_width_adapter:in_endofpacket
	wire          mm_bridge_0_m0_rsp_width_adapter_src_valid;                         // mm_bridge_0_m0_rsp_width_adapter:out_valid -> mm_bridge_0_m0_agent:rp_valid
	wire   [83:0] mm_bridge_0_m0_rsp_width_adapter_src_data;                          // mm_bridge_0_m0_rsp_width_adapter:out_data -> mm_bridge_0_m0_agent:rp_data
	wire          mm_bridge_0_m0_rsp_width_adapter_src_ready;                         // mm_bridge_0_m0_agent:rp_ready -> mm_bridge_0_m0_rsp_width_adapter:out_ready
	wire    [1:0] mm_bridge_0_m0_rsp_width_adapter_src_channel;                       // mm_bridge_0_m0_rsp_width_adapter:out_channel -> mm_bridge_0_m0_agent:rp_channel
	wire          mm_bridge_0_m0_rsp_width_adapter_src_startofpacket;                 // mm_bridge_0_m0_rsp_width_adapter:out_startofpacket -> mm_bridge_0_m0_agent:rp_startofpacket
	wire          mm_bridge_0_m0_rsp_width_adapter_src_endofpacket;                   // mm_bridge_0_m0_rsp_width_adapter:out_endofpacket -> mm_bridge_0_m0_agent:rp_endofpacket
	wire          router_src_valid;                                                   // router:src_valid -> mm_bridge_0_m0_cmd_width_adapter:in_valid
	wire   [83:0] router_src_data;                                                    // router:src_data -> mm_bridge_0_m0_cmd_width_adapter:in_data
	wire          router_src_ready;                                                   // mm_bridge_0_m0_cmd_width_adapter:in_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                 // router:src_channel -> mm_bridge_0_m0_cmd_width_adapter:in_channel
	wire          router_src_startofpacket;                                           // router:src_startofpacket -> mm_bridge_0_m0_cmd_width_adapter:in_startofpacket
	wire          router_src_endofpacket;                                             // router:src_endofpacket -> mm_bridge_0_m0_cmd_width_adapter:in_endofpacket
	wire          mm_bridge_0_m0_cmd_width_adapter_src_valid;                         // mm_bridge_0_m0_cmd_width_adapter:out_valid -> cmd_demux:sink_valid
	wire  [101:0] mm_bridge_0_m0_cmd_width_adapter_src_data;                          // mm_bridge_0_m0_cmd_width_adapter:out_data -> cmd_demux:sink_data
	wire          mm_bridge_0_m0_cmd_width_adapter_src_ready;                         // cmd_demux:sink_ready -> mm_bridge_0_m0_cmd_width_adapter:out_ready
	wire    [1:0] mm_bridge_0_m0_cmd_width_adapter_src_channel;                       // mm_bridge_0_m0_cmd_width_adapter:out_channel -> cmd_demux:sink_channel
	wire          mm_bridge_0_m0_cmd_width_adapter_src_startofpacket;                 // mm_bridge_0_m0_cmd_width_adapter:out_startofpacket -> cmd_demux:sink_startofpacket
	wire          mm_bridge_0_m0_cmd_width_adapter_src_endofpacket;                   // mm_bridge_0_m0_cmd_width_adapter:out_endofpacket -> cmd_demux:sink_endofpacket
	wire          modular_adc_0_sequencer_csr_agent_rdata_fifo_src_valid;             // modular_adc_0_sequencer_csr_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] modular_adc_0_sequencer_csr_agent_rdata_fifo_src_data;              // modular_adc_0_sequencer_csr_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          modular_adc_0_sequencer_csr_agent_rdata_fifo_src_ready;             // avalon_st_adapter:in_0_ready -> modular_adc_0_sequencer_csr_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                      // avalon_st_adapter:out_0_valid -> modular_adc_0_sequencer_csr_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                       // avalon_st_adapter:out_0_data -> modular_adc_0_sequencer_csr_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                      // modular_adc_0_sequencer_csr_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                      // avalon_st_adapter:out_0_error -> modular_adc_0_sequencer_csr_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (10),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) mm_bridge_0_m0_translator (
		.clk                    (clk_0_clk_clk),                                                     //                       clk.clk
		.reset                  (mm_bridge_0_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (mm_bridge_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (mm_bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (mm_bridge_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (mm_bridge_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (mm_bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (mm_bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (mm_bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (mm_bridge_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (mm_bridge_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (mm_bridge_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (mm_bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (mm_bridge_0_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (mm_bridge_0_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (mm_bridge_0_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (mm_bridge_0_m0_byteenable),                                         //                          .byteenable
		.av_read                (mm_bridge_0_m0_read),                                               //                          .read
		.av_readdata            (mm_bridge_0_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (mm_bridge_0_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (mm_bridge_0_m0_write),                                              //                          .write
		.av_writedata           (mm_bridge_0_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (mm_bridge_0_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                              //               (terminated)
		.av_begintransfer       (1'b0),                                                              //               (terminated)
		.av_chipselect          (1'b0),                                                              //               (terminated)
		.av_lock                (1'b0),                                                              //               (terminated)
		.uav_clken              (),                                                                  //               (terminated)
		.av_clken               (1'b1),                                                              //               (terminated)
		.uav_response           (2'b00),                                                             //               (terminated)
		.av_response            (),                                                                  //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                              //               (terminated)
		.av_writeresponsevalid  ()                                                                   //               (terminated)
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) master_0_master_translator (
		.clk                    (clk_0_clk_clk),                                                      //                       clk.clk
		.reset                  (mm_bridge_0_reset_reset_bridge_in_reset_reset),                      //                     reset.reset
		.uav_address            (master_0_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (master_0_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (master_0_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (master_0_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (master_0_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (master_0_master_byteenable),                                         //                          .byteenable
		.av_read                (master_0_master_read),                                               //                          .read
		.av_readdata            (master_0_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (master_0_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (master_0_master_write),                                              //                          .write
		.av_writedata           (master_0_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                               //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1),                                                               //               (terminated)
		.uav_response           (2'b00),                                                              //               (terminated)
		.av_response            (),                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) modular_adc_0_sequencer_csr_translator (
		.clk                    (clk_0_clk_clk),                                      //                      clk.clk
		.reset                  (mm_bridge_0_reset_reset_bridge_in_reset_reset),      //                    reset.reset
		.uav_address            (modular_adc_0_sequencer_csr_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (modular_adc_0_sequencer_csr_agent_m0_burstcount),    //                         .burstcount
		.uav_read               (modular_adc_0_sequencer_csr_agent_m0_read),          //                         .read
		.uav_write              (modular_adc_0_sequencer_csr_agent_m0_write),         //                         .write
		.uav_waitrequest        (modular_adc_0_sequencer_csr_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (modular_adc_0_sequencer_csr_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (modular_adc_0_sequencer_csr_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata           (modular_adc_0_sequencer_csr_agent_m0_readdata),      //                         .readdata
		.uav_writedata          (modular_adc_0_sequencer_csr_agent_m0_writedata),     //                         .writedata
		.uav_lock               (modular_adc_0_sequencer_csr_agent_m0_lock),          //                         .lock
		.uav_debugaccess        (modular_adc_0_sequencer_csr_agent_m0_debugaccess),   //                         .debugaccess
		.av_address             (modular_adc_0_sequencer_csr_address),                //      avalon_anti_slave_0.address
		.av_write               (modular_adc_0_sequencer_csr_write),                  //                         .write
		.av_read                (modular_adc_0_sequencer_csr_read),                   //                         .read
		.av_readdata            (modular_adc_0_sequencer_csr_readdata),               //                         .readdata
		.av_writedata           (modular_adc_0_sequencer_csr_writedata),              //                         .writedata
		.av_begintransfer       (),                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                   //              (terminated)
		.av_burstcount          (),                                                   //              (terminated)
		.av_byteenable          (),                                                   //              (terminated)
		.av_readdatavalid       (1'b0),                                               //              (terminated)
		.av_waitrequest         (1'b0),                                               //              (terminated)
		.av_writebyteenable     (),                                                   //              (terminated)
		.av_lock                (),                                                   //              (terminated)
		.av_chipselect          (),                                                   //              (terminated)
		.av_clken               (),                                                   //              (terminated)
		.uav_clken              (1'b0),                                               //              (terminated)
		.av_debugaccess         (),                                                   //              (terminated)
		.av_outputenable        (),                                                   //              (terminated)
		.uav_response           (),                                                   //              (terminated)
		.av_response            (2'b00),                                              //              (terminated)
		.uav_writeresponsevalid (),                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (83),
		.PKT_ORI_BURST_SIZE_L      (81),
		.PKT_RESPONSE_STATUS_H     (80),
		.PKT_RESPONSE_STATUS_L     (79),
		.PKT_QOS_H                 (68),
		.PKT_QOS_L                 (68),
		.PKT_DATA_SIDEBAND_H       (66),
		.PKT_DATA_SIDEBAND_L       (66),
		.PKT_ADDR_SIDEBAND_H       (65),
		.PKT_ADDR_SIDEBAND_L       (65),
		.PKT_BURST_TYPE_H          (64),
		.PKT_BURST_TYPE_L          (63),
		.PKT_CACHE_H               (78),
		.PKT_CACHE_L               (75),
		.PKT_THREAD_ID_H           (71),
		.PKT_THREAD_ID_L           (71),
		.PKT_BURST_SIZE_H          (62),
		.PKT_BURST_SIZE_L          (60),
		.PKT_TRANS_EXCLUSIVE       (55),
		.PKT_TRANS_LOCK            (54),
		.PKT_BEGIN_BURST           (67),
		.PKT_PROTECTION_H          (74),
		.PKT_PROTECTION_L          (72),
		.PKT_BURSTWRAP_H           (59),
		.PKT_BURSTWRAP_L           (59),
		.PKT_BYTE_CNT_H            (58),
		.PKT_BYTE_CNT_L            (56),
		.PKT_ADDR_H                (49),
		.PKT_ADDR_L                (18),
		.PKT_TRANS_COMPRESSED_READ (50),
		.PKT_TRANS_POSTED          (51),
		.PKT_TRANS_WRITE           (52),
		.PKT_TRANS_READ            (53),
		.PKT_DATA_H                (15),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_SRC_ID_H              (69),
		.PKT_SRC_ID_L              (69),
		.PKT_DEST_ID_H             (70),
		.PKT_DEST_ID_L             (70),
		.ST_DATA_W                 (84),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (2),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) mm_bridge_0_m0_agent (
		.clk                   (clk_0_clk_clk),                                                     //       clk.clk
		.reset                 (mm_bridge_0_reset_reset_bridge_in_reset_reset),                     // clk_reset.reset
		.av_address            (mm_bridge_0_m0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (mm_bridge_0_m0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (mm_bridge_0_m0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (mm_bridge_0_m0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (mm_bridge_0_m0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (mm_bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (mm_bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (mm_bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (mm_bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (mm_bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (mm_bridge_0_m0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (mm_bridge_0_m0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (mm_bridge_0_m0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (mm_bridge_0_m0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (mm_bridge_0_m0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (mm_bridge_0_m0_agent_cp_ready),                                     //          .ready
		.rp_valid              (mm_bridge_0_m0_rsp_width_adapter_src_valid),                        //        rp.valid
		.rp_data               (mm_bridge_0_m0_rsp_width_adapter_src_data),                         //          .data
		.rp_channel            (mm_bridge_0_m0_rsp_width_adapter_src_channel),                      //          .channel
		.rp_startofpacket      (mm_bridge_0_m0_rsp_width_adapter_src_startofpacket),                //          .startofpacket
		.rp_endofpacket        (mm_bridge_0_m0_rsp_width_adapter_src_endofpacket),                  //          .endofpacket
		.rp_ready              (mm_bridge_0_m0_rsp_width_adapter_src_ready),                        //          .ready
		.av_response           (),                                                                  // (terminated)
		.av_writeresponsevalid ()                                                                   // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (101),
		.PKT_ORI_BURST_SIZE_L      (99),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.PKT_QOS_H                 (86),
		.PKT_QOS_L                 (86),
		.PKT_DATA_SIDEBAND_H       (84),
		.PKT_DATA_SIDEBAND_L       (84),
		.PKT_ADDR_SIDEBAND_H       (83),
		.PKT_ADDR_SIDEBAND_L       (83),
		.PKT_BURST_TYPE_H          (82),
		.PKT_BURST_TYPE_L          (81),
		.PKT_CACHE_H               (96),
		.PKT_CACHE_L               (93),
		.PKT_THREAD_ID_H           (89),
		.PKT_THREAD_ID_L           (89),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (85),
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.ST_DATA_W                 (102),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) master_0_master_agent (
		.clk                   (clk_0_clk_clk),                                                      //       clk.clk
		.reset                 (mm_bridge_0_reset_reset_bridge_in_reset_reset),                      // clk_reset.reset
		.av_address            (master_0_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (master_0_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (master_0_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (master_0_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (master_0_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (master_0_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (master_0_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (master_0_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_001_src_valid),                                              //        rp.valid
		.rp_data               (rsp_mux_001_src_data),                                               //          .data
		.rp_channel            (rsp_mux_001_src_channel),                                            //          .channel
		.rp_startofpacket      (rsp_mux_001_src_startofpacket),                                      //          .startofpacket
		.rp_endofpacket        (rsp_mux_001_src_endofpacket),                                        //          .endofpacket
		.rp_ready              (rsp_mux_001_src_ready),                                              //          .ready
		.av_response           (),                                                                   // (terminated)
		.av_writeresponsevalid ()                                                                    // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (101),
		.PKT_ORI_BURST_SIZE_L      (99),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (85),
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (102),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) modular_adc_0_sequencer_csr_agent (
		.clk                     (clk_0_clk_clk),                                                //             clk.clk
		.reset                   (mm_bridge_0_reset_reset_bridge_in_reset_reset),                //       clk_reset.reset
		.m0_address              (modular_adc_0_sequencer_csr_agent_m0_address),                 //              m0.address
		.m0_burstcount           (modular_adc_0_sequencer_csr_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (modular_adc_0_sequencer_csr_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (modular_adc_0_sequencer_csr_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (modular_adc_0_sequencer_csr_agent_m0_lock),                    //                .lock
		.m0_readdata             (modular_adc_0_sequencer_csr_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (modular_adc_0_sequencer_csr_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (modular_adc_0_sequencer_csr_agent_m0_read),                    //                .read
		.m0_waitrequest          (modular_adc_0_sequencer_csr_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (modular_adc_0_sequencer_csr_agent_m0_writedata),               //                .writedata
		.m0_write                (modular_adc_0_sequencer_csr_agent_m0_write),                   //                .write
		.rp_endofpacket          (modular_adc_0_sequencer_csr_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (modular_adc_0_sequencer_csr_agent_rp_ready),                   //                .ready
		.rp_valid                (modular_adc_0_sequencer_csr_agent_rp_valid),                   //                .valid
		.rp_data                 (modular_adc_0_sequencer_csr_agent_rp_data),                    //                .data
		.rp_startofpacket        (modular_adc_0_sequencer_csr_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                            //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                            //                .valid
		.cp_data                 (cmd_mux_src_data),                                             //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                                    //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                      //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                          //                .channel
		.rf_sink_ready           (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (modular_adc_0_sequencer_csr_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (modular_adc_0_sequencer_csr_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (modular_adc_0_sequencer_csr_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (modular_adc_0_sequencer_csr_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (modular_adc_0_sequencer_csr_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                 //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                //                .error
		.rdata_fifo_src_ready    (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                        //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                          //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (103),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) modular_adc_0_sequencer_csr_agent_rsp_fifo (
		.clk               (clk_0_clk_clk),                                                //       clk.clk
		.reset             (mm_bridge_0_reset_reset_bridge_in_reset_reset),                // clk_reset.reset
		.in_data           (modular_adc_0_sequencer_csr_agent_rf_source_data),             //        in.data
		.in_valid          (modular_adc_0_sequencer_csr_agent_rf_source_valid),            //          .valid
		.in_ready          (modular_adc_0_sequencer_csr_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (modular_adc_0_sequencer_csr_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (modular_adc_0_sequencer_csr_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (modular_adc_0_sequencer_csr_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                        // (terminated)
		.csr_read          (1'b0),                                                         // (terminated)
		.csr_write         (1'b0),                                                         // (terminated)
		.csr_readdata      (),                                                             // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                         // (terminated)
		.almost_full_data  (),                                                             // (terminated)
		.almost_empty_data (),                                                             // (terminated)
		.in_empty          (1'b0),                                                         // (terminated)
		.out_empty         (),                                                             // (terminated)
		.in_error          (1'b0),                                                         // (terminated)
		.out_error         (),                                                             // (terminated)
		.in_channel        (1'b0),                                                         // (terminated)
		.out_channel       ()                                                              // (terminated)
	);

	ADC_mm_interconnect_0_router router (
		.sink_ready         (mm_bridge_0_m0_agent_cp_ready),                 //      sink.ready
		.sink_valid         (mm_bridge_0_m0_agent_cp_valid),                 //          .valid
		.sink_data          (mm_bridge_0_m0_agent_cp_data),                  //          .data
		.sink_startofpacket (mm_bridge_0_m0_agent_cp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (mm_bridge_0_m0_agent_cp_endofpacket),           //          .endofpacket
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                              //       src.ready
		.src_valid          (router_src_valid),                              //          .valid
		.src_data           (router_src_data),                               //          .data
		.src_channel        (router_src_channel),                            //          .channel
		.src_startofpacket  (router_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                         //          .endofpacket
	);

	ADC_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (master_0_master_agent_cp_ready),                //      sink.ready
		.sink_valid         (master_0_master_agent_cp_valid),                //          .valid
		.sink_data          (master_0_master_agent_cp_data),                 //          .data
		.sink_startofpacket (master_0_master_agent_cp_startofpacket),        //          .startofpacket
		.sink_endofpacket   (master_0_master_agent_cp_endofpacket),          //          .endofpacket
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                          //       src.ready
		.src_valid          (router_001_src_valid),                          //          .valid
		.src_data           (router_001_src_data),                           //          .data
		.src_channel        (router_001_src_channel),                        //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                  //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                     //          .endofpacket
	);

	ADC_mm_interconnect_0_router_002 router_002 (
		.sink_ready         (modular_adc_0_sequencer_csr_agent_rp_ready),         //      sink.ready
		.sink_valid         (modular_adc_0_sequencer_csr_agent_rp_valid),         //          .valid
		.sink_data          (modular_adc_0_sequencer_csr_agent_rp_data),          //          .data
		.sink_startofpacket (modular_adc_0_sequencer_csr_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (modular_adc_0_sequencer_csr_agent_rp_endofpacket),   //          .endofpacket
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.src_ready          (router_002_src_ready),                               //       src.ready
		.src_valid          (router_002_src_valid),                               //          .valid
		.src_data           (router_002_src_data),                                //          .data
		.src_channel        (router_002_src_channel),                             //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                       //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                          //          .endofpacket
	);

	ADC_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.sink_ready         (mm_bridge_0_m0_cmd_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (mm_bridge_0_m0_cmd_width_adapter_src_channel),       //          .channel
		.sink_data          (mm_bridge_0_m0_cmd_width_adapter_src_data),          //          .data
		.sink_startofpacket (mm_bridge_0_m0_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (mm_bridge_0_m0_cmd_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (mm_bridge_0_m0_cmd_width_adapter_src_valid),         //          .valid
		.src0_ready         (cmd_demux_src0_ready),                               //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                               //          .valid
		.src0_data          (cmd_demux_src0_data),                                //          .data
		.src0_channel       (cmd_demux_src0_channel),                             //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                       //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                          //          .endofpacket
	);

	ADC_mm_interconnect_0_cmd_demux cmd_demux_001 (
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                          //      sink.ready
		.sink_channel       (router_001_src_channel),                        //          .channel
		.sink_data          (router_001_src_data),                           //          .data
		.sink_startofpacket (router_001_src_startofpacket),                  //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                    //          .endofpacket
		.sink_valid         (router_001_src_valid),                          //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                      //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                      //          .valid
		.src0_data          (cmd_demux_001_src0_data),                       //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                    //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),              //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                 //          .endofpacket
	);

	ADC_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (clk_0_clk_clk),                                 //       clk.clk
		.reset               (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                             //       src.ready
		.src_valid           (cmd_mux_src_valid),                             //          .valid
		.src_data            (cmd_mux_src_data),                              //          .data
		.src_channel         (cmd_mux_src_channel),                           //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                     //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                       //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                          //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                          //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                        //          .channel
		.sink0_data          (cmd_demux_src0_data),                           //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                  //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),                    //          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                      //     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                      //          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),                    //          .channel
		.sink1_data          (cmd_demux_001_src0_data),                       //          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),              //          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)                 //          .endofpacket
	);

	ADC_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                          //      sink.ready
		.sink_channel       (router_002_src_channel),                        //          .channel
		.sink_data          (router_002_src_data),                           //          .data
		.sink_startofpacket (router_002_src_startofpacket),                  //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                    //          .endofpacket
		.sink_valid         (router_002_src_valid),                          //          .valid
		.src0_ready         (rsp_demux_src0_ready),                          //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                          //          .valid
		.src0_data          (rsp_demux_src0_data),                           //          .data
		.src0_channel       (rsp_demux_src0_channel),                        //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                  //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                    //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                          //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                          //          .valid
		.src1_data          (rsp_demux_src1_data),                           //          .data
		.src1_channel       (rsp_demux_src1_channel),                        //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                  //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                     //          .endofpacket
	);

	ADC_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (clk_0_clk_clk),                                 //       clk.clk
		.reset               (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                             //       src.ready
		.src_valid           (rsp_mux_src_valid),                             //          .valid
		.src_data            (rsp_mux_src_data),                              //          .data
		.src_channel         (rsp_mux_src_channel),                           //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                     //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                       //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                          //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                          //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                        //          .channel
		.sink0_data          (rsp_demux_src0_data),                           //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                  //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                     //          .endofpacket
	);

	ADC_mm_interconnect_0_rsp_mux rsp_mux_001 (
		.clk                 (clk_0_clk_clk),                                 //       clk.clk
		.reset               (mm_bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                         //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                         //          .valid
		.src_data            (rsp_mux_001_src_data),                          //          .data
		.src_channel         (rsp_mux_001_src_channel),                       //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                 //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                   //          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                          //     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                          //          .valid
		.sink0_channel       (rsp_demux_src1_channel),                        //          .channel
		.sink0_data          (rsp_demux_src1_data),                           //          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),                  //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)                     //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (76),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_TRANS_WRITE            (70),
		.IN_PKT_BURSTWRAP_H            (77),
		.IN_PKT_BURSTWRAP_L            (77),
		.IN_PKT_BURST_SIZE_H           (80),
		.IN_PKT_BURST_SIZE_L           (78),
		.IN_PKT_RESPONSE_STATUS_H      (98),
		.IN_PKT_RESPONSE_STATUS_L      (97),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (82),
		.IN_PKT_BURST_TYPE_L           (81),
		.IN_PKT_ORI_BURST_SIZE_L       (99),
		.IN_PKT_ORI_BURST_SIZE_H       (101),
		.IN_ST_DATA_W                  (102),
		.OUT_PKT_ADDR_H                (49),
		.OUT_PKT_ADDR_L                (18),
		.OUT_PKT_DATA_H                (15),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (17),
		.OUT_PKT_BYTEEN_L              (16),
		.OUT_PKT_BYTE_CNT_H            (58),
		.OUT_PKT_BYTE_CNT_L            (56),
		.OUT_PKT_TRANS_COMPRESSED_READ (50),
		.OUT_PKT_BURST_SIZE_H          (62),
		.OUT_PKT_BURST_SIZE_L          (60),
		.OUT_PKT_RESPONSE_STATUS_H     (80),
		.OUT_PKT_RESPONSE_STATUS_L     (79),
		.OUT_PKT_TRANS_EXCLUSIVE       (55),
		.OUT_PKT_BURST_TYPE_H          (64),
		.OUT_PKT_BURST_TYPE_L          (63),
		.OUT_PKT_ORI_BURST_SIZE_L      (81),
		.OUT_PKT_ORI_BURST_SIZE_H      (83),
		.OUT_ST_DATA_W                 (84),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) mm_bridge_0_m0_rsp_width_adapter (
		.clk                  (clk_0_clk_clk),                                      //       clk.clk
		.reset                (mm_bridge_0_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.in_valid             (rsp_mux_src_valid),                                  //      sink.valid
		.in_channel           (rsp_mux_src_channel),                                //          .channel
		.in_startofpacket     (rsp_mux_src_startofpacket),                          //          .startofpacket
		.in_endofpacket       (rsp_mux_src_endofpacket),                            //          .endofpacket
		.in_ready             (rsp_mux_src_ready),                                  //          .ready
		.in_data              (rsp_mux_src_data),                                   //          .data
		.out_endofpacket      (mm_bridge_0_m0_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (mm_bridge_0_m0_rsp_width_adapter_src_data),          //          .data
		.out_channel          (mm_bridge_0_m0_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (mm_bridge_0_m0_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (mm_bridge_0_m0_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (mm_bridge_0_m0_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                              // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (49),
		.IN_PKT_ADDR_L                 (18),
		.IN_PKT_DATA_H                 (15),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (17),
		.IN_PKT_BYTEEN_L               (16),
		.IN_PKT_BYTE_CNT_H             (58),
		.IN_PKT_BYTE_CNT_L             (56),
		.IN_PKT_TRANS_COMPRESSED_READ  (50),
		.IN_PKT_TRANS_WRITE            (52),
		.IN_PKT_BURSTWRAP_H            (59),
		.IN_PKT_BURSTWRAP_L            (59),
		.IN_PKT_BURST_SIZE_H           (62),
		.IN_PKT_BURST_SIZE_L           (60),
		.IN_PKT_RESPONSE_STATUS_H      (80),
		.IN_PKT_RESPONSE_STATUS_L      (79),
		.IN_PKT_TRANS_EXCLUSIVE        (55),
		.IN_PKT_BURST_TYPE_H           (64),
		.IN_PKT_BURST_TYPE_L           (63),
		.IN_PKT_ORI_BURST_SIZE_L       (81),
		.IN_PKT_ORI_BURST_SIZE_H       (83),
		.IN_ST_DATA_W                  (84),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (76),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (80),
		.OUT_PKT_BURST_SIZE_L          (78),
		.OUT_PKT_RESPONSE_STATUS_H     (98),
		.OUT_PKT_RESPONSE_STATUS_L     (97),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (82),
		.OUT_PKT_BURST_TYPE_L          (81),
		.OUT_PKT_ORI_BURST_SIZE_L      (99),
		.OUT_PKT_ORI_BURST_SIZE_H      (101),
		.OUT_ST_DATA_W                 (102),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) mm_bridge_0_m0_cmd_width_adapter (
		.clk                  (clk_0_clk_clk),                                      //       clk.clk
		.reset                (mm_bridge_0_reset_reset_bridge_in_reset_reset),      // clk_reset.reset
		.in_valid             (router_src_valid),                                   //      sink.valid
		.in_channel           (router_src_channel),                                 //          .channel
		.in_startofpacket     (router_src_startofpacket),                           //          .startofpacket
		.in_endofpacket       (router_src_endofpacket),                             //          .endofpacket
		.in_ready             (router_src_ready),                                   //          .ready
		.in_data              (router_src_data),                                    //          .data
		.out_endofpacket      (mm_bridge_0_m0_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (mm_bridge_0_m0_cmd_width_adapter_src_data),          //          .data
		.out_channel          (mm_bridge_0_m0_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (mm_bridge_0_m0_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (mm_bridge_0_m0_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (mm_bridge_0_m0_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                              // (terminated)
	);

	ADC_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_0_clk_clk),                                          // in_clk_0.clk
		.in_rst_0_reset (mm_bridge_0_reset_reset_bridge_in_reset_reset),          // in_rst_0.reset
		.in_0_data      (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_data),  //     in_0.data
		.in_0_valid     (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_valid), //         .valid
		.in_0_ready     (modular_adc_0_sequencer_csr_agent_rdata_fifo_src_ready), //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                           //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                          //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                          //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                           //         .error
	);

endmodule
